require('./traceur-runtime');
"use strict";
var SubstitutionCipher = require('./substitution-cipher');
var Caesar = require('./caesar');
var ROT5 = require('./rot5');
var ROT13 = require('./rot13');
var ROT18 = require('./rot18');
var ROT47 = require('./rot47');
var Vigenere = require('./vigenere');
var CaesarSalad = {};
CaesarSalad.ciphers = [Caesar.name, ROT5.name, ROT13.name, ROT18.name, ROT47.name, Vigenere.name];
CaesarSalad.SubstitutionCipher = SubstitutionCipher;
CaesarSalad.Caesar = Caesar;
CaesarSalad.ROT5 = ROT5;
CaesarSalad.ROT13 = ROT13;
CaesarSalad.ROT18 = ROT18;
CaesarSalad.ROT47 = ROT47;
CaesarSalad.Vigenere = Vigenere;
CaesarSalad['default'] = CaesarSalad;
module.exports = CaesarSalad;
